name: Build PokeReader

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zaksabeast/devkitarm-rust

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PokeReader
          path: out/default.3gx
